language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors

stages:
  - test

matrix:
  fast_finish: true
  include:
    - stage: test
      php: 7.0
    - stage: test
      php: 7.1
    - stage: test
      php: 7.2
    - stage: test
      php: 7.3

before_install:
  - phpenv config-add .ci/travis.php.ini

install:
  - make install

script:
  - make test

notifications:
  email: silasjoisten@gmail.com
