language: php
sudo: false
dist: trusty

php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit
    - vendor
env:
  global:
    - SYMFONY_PHPUNIT_DIR=.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=weak

before_install:
  - phpenv config-add .ci/travis.php.ini
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --classmap-authoritative --optimize-autoloader -vvv

script:
  - vendor/bin/phpunit

notifications:
  email: silasjoisten@gmail.com