language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - stage: test
      php: '7.2'
    - stage: test
      php: '7.3'

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit
    - vendor
env:
  global:
    - SYMFONY_PHPUNIT_DIR=.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors

before_install:
  - phpenv config-add .ci/travis.php.ini
  - phpenv config-rm xdebug.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit

notifications:
  email: silasjoisten@gmail.com
