language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors

stages:
  - lint
  - test
  - future

matrix:
  fast_finish: true
  include:
    - stage: lint
      php: 7.2
      script: make cs
    - stage: test
      php: 5.6
    - stage: test
      php: 7.0
    - stage: test
      php: 7.1
    - stage: test
      php: 7.2

before_install:
  - phpenv config-add .ci/travis.php.ini

install:
  - make install

script:
  - make test

notifications:
  email: silas.joisten@hotmail.de
